### ISSUE TITLE
Using default files doesn't follow the expected location

### ISSUE THREAD

**Issue by papoteur-mga** [lxqt/lxqt-session#365] opened 2021-02-13 12:55 UTC
According to this commit https://github.com/lxqt/lxqt-session/commit/3e39f49465f9b7b73261ba69e3b83a27fb6b9253#diff-3a2978c84b7d4bd02ebbfc37fe2717a94ca558d1c016d7e356e43382773312d1
lxqt.conf should land in /usr/share/lxqt.
However, in this case, the first session doesn't use this file, but look for the "old" location in /etc/xdg/lxqt.
##### Expected Behavior
A first session for a new user should use lxqt.conf for defining icon-theme.
##### Current Behavior
When the default file is in /usr/share/lxqt, a new session has no icons. lxqt.conf contains:
> [General]
> __userfile__=true
When the default file is in /etc/xdg/lxqt, a new session looks fine, using the default icon theme.

##### System Information
* Distribution & Version: Mageia Cauldron
* Qt Version: 5.15.2
* liblxqt Version: 0.16.0

**Comment by tsujan** [comment] 2021-02-13 13:31
> but look for the "old" location in /etc/xdg/lxq

That location isn't old and has (can have) priority over `/usr/share/lxqt`. See `echo $XDG_CONFIG_DIRS` and the order in its output.

Please attach the files in your `/etc/xdg/lxqt`.

**Comment by papoteur-mga** [comment] 2021-02-13 13:40
echo $XDG_CONFIG_DIRS
/etc:/etc/xdg:/usr/share
In /etc/xdg/lxqt, I have
globalkeyshortcuts.conf
panel.conf

**Comment by papoteur-mga** [comment] 2021-02-13 13:46
[conf.tar.gz](https://github.com/lxqt/lxqt-session/files/5975766/conf.tar.gz)

**Comment by tsujan** [comment] 2021-02-13 14:00
Thanks!

Apps should follow the order in `XDG_CONFIG_DIRS`. Since you don't have `lxqt.conf` in `/etc/xdg/`, the one in `/usr/share/lxqt/` should be read; if not (as your report tells), there is a bug.

@luis-pereira, doesn't `lxqt-session` follow `QStandardPaths` (which is the freedesktop standard)?

**Comment by tsujan** [comment] 2021-02-13 14:09
@papoteur-mga 

I forgot to ask an important question. `/usr/share/lxqt/lxqt.conf` should be:

```
[General]
theme=frost
icon_theme=oxygen
single_click_activate=false
tool_button_style=ToolButtonTextBesideIcon

[Qt]
font="Sans,11,-1,5,50,0,0,0,0,0"
doubleClickInterval=400
style=Fusion
wheelScrollLines=3
```

Isn't that so on your system?

**Comment by papoteur-mga** [comment] 2021-02-13 16:16
Hello tsujan
The file is customized by the distribution:
`[General]
theme=system
icon_theme=breeze
single_click_activate=false
tool_button_style=ToolButtonTextBesideIcon

[Qt]
font="Sans,11,-1,5,50,0,0,0,0,0"
doubleClickInterval=400
style=Fusion
wheelScrollLines=3`

**Comment by tsujan** [comment] 2021-02-13 16:25
The file is OK. I'll test by creating a new user when I find the time.

**Comment by tsujan** [comment] 2021-02-13 17:43
I found some time and tested with a newly created user. I'm afraid the problem is NOT reproducible, whether with the default LXQt config file(s) or with yours, whether without `/etc/xdg/lxqt` or with your attached files. For each test, I removed the whole `~/.config/lxqt` of the new user from inside my default user, before logging as the new user.

The problem you see may be related to your distro builds, bad patches, etc -- there's not enough info for a good guess -- but it isn't in LXQt. Hence closing.

**Closed by tsujan** 2021-02-13 17:43 UTC
